# Generated by Django 4.1.3 on 2023-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeeshaLarsenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
