# Generated by Django 4.1.3 on 2023-09-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeeshaLarsenapp', '0006_alter_userprofile_address_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
